"""Add last_topup_date to wallets table

Revision ID: a315b31ddf24
Revises: 83534d9c1245
Create Date: 2025-10-22 23:18:07.078275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a315b31ddf24'
down_revision = '83534d9c1245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_topup_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('last_topup_date')

    # ### end Alembic commands ###
